[tools]
nodejs = '24.10.0'

[tasks]
deps = 'npm ci'

[tasks.build]
run = 'npm run build'
depends = ['deps']

[tasks.dist]
depends = ['build']
run = [
  'rm -rf node_modules',
  'npm ci --omit=dev --omit=optional'
]
