name: Test
permissions:
  contents: read
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false
    - uses: jdx/mise-action@v4.1.0 # zizmor: ignore[unpinned-uses] immutable tag
    - run: mise lint
    - uses: ./
